name: Miles Stevens
favicon: null
layout_spectrum: 0.50465
typography_spectrum: 0.09467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8f3'
    - '#3d3737'
    - '#ccc8be'
    - '#4d9fd2'
    - '#c69439'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
